<template>
  <v-container ref="afd" style="position: relative">
    <slot ref="slot2"></slot>
    <v-btn
      @click="share"
      color="#016f94"
      fab
      dark
      style="position: absolute; right: 0; top: 0"
      :loading="loading"
      data-html2canvas-ignore
    >
      {{ $vuetify.breakpoint.name }}
      <v-icon size="35" v-if="canShare">mdi-share</v-icon>
      <v-icon size="35" v-else>mdi-download</v-icon>
    </v-btn>
  </v-container>
</template>

<script>
import { downloadBase64File } from "~/functions/utils";
import html2canvas from "html2canvas";

export default {
  name: "Share",
  props: {
    imageName: {
      type: String,
      default: "whatsanalyze.png",
    },
    useHtml2Canvas: {
      type: Boolean,
      default: false,
    },
  },
  data() {
    return {
      canShare:
        (navigator.share &&
          navigator.canShare &&
          navigator.canShare({
            files: [new File([], "image.png", { type: "image/png" })],
          })) ||
        false,
      loading: false,
    };
  },
  methods: {
    async getCanvas() {
      if (this.useHtml2Canvas) {
        // extremly ugly but could not find a way around this
        // scrollY somehow is ignored in the html2canvas options
        let currScroll = window.scrollY;

        let offset = 0;
        if (this.$vuetify.breakpoint.xsOnly) {
          offset = 340;
        } else if (this.$vuetify.breakpoint.smOnly) {
          offset = 280;
        } else if (this.$vuetify.breakpoint.mdAndUp) {
          offset = 260;
        }
        window.scrollTo(0, offset);
        return html2canvas(this.$slots.default[0].child.$el).then((_) => {
          window.scrollTo(0, currScroll);
          return _;
        });
      } else {
        return this.$slots.default[0].child.$refs.canvas;
      }
    },
    async share() {
      let chartName = this.$slots.default[0].componentOptions.tag;
      this.loading = true;
      let canvas = await this.getCanvas();
      this.loading = false;

      if (this.canShare) {
        this.$gtag.event("download-graph", {
          event_category: "graph",
          event_label: chartName + "-share-pressed",
          value: "1",
        });
        canvas.toBlob((blob) => {
          navigator
            .share({
              title: "WhatsAnalze.com",
              text:
                "Have a look at this graph of our conversation, generated by whatsanalyze.com.",
              files: [
                new File([blob], chartName + "-" + this.imageName, {
                  type: "image/png",
                }),
              ],
            })
            .then(() => {
              this.$gtag.event("download-graph", {
                event_category: "graph",
                event_label: chartName + "-shared",
                value: "1",
              });
            });
        });
      } else {
        this.$gtag.event("download-graph", {
          event_category: "graph",
          event_label: chartName + "-download-pressed",
          value: "1",
        });
        downloadBase64File(
          canvas.toDataURL(),
          chartName + "-" + this.imageName
        );
        this.$gtag.event("download-graph", {
          event_category: "graph",
          event_label: chartName + "-downloaded",
          value: "1",
        });
      }
    },
  },
};
</script>

<style scoped></style>
