<template>
  <v-container ref="afd" style="position: relative">
    <slot ref="slot2"></slot>
    <v-btn
      @click="share"
      color="#016f94"
      fab
      dark
      style="position: absolute; right: 0; top: 0"
      ><v-icon size="35">mdi-download</v-icon></v-btn
    >
  </v-container>
</template>

<script>
export default {
  name: "Share",
  props: {
    imageName: {
      type: String,
      default: "shareGraph.png",
    },
  },
  data() {
    return {
      canShare:
        (navigator.share &&
          navigator.canShare &&
          navigator.canShare({
            files: [new File([], "image.png", { type: "image/png" })],
          })) ||
        false,
      loading: false,
    };
  },
  methods: {
    downloadBase64File(contentBase64, fileName) {
      const downloadLink = document.createElement("a");
      document.body.appendChild(downloadLink);

      downloadLink.href = contentBase64;
      downloadLink.target = "_self";
      downloadLink.download = fileName;
      downloadLink.click();
      document.body.removeChild(downloadLink);
    },
    share() {
      if (this.canShare) {
        this.loading = true;
        this.$slots.default[0].child.$refs.canvas.toBlob((blob) => {
          navigator
            .share({
              title: "WhatsAnalze.com",
              text:
                "Have a look at this graph of our conversation, generated by whatsanalyze.com.",
              files: [new File([blob], this.imageName, { type: "image/png" })],
            })
            .then(() => (this.loading = false))
            .catch(() => (this.loading = false));
        });
      } else {
        let a = this.$slots.default[0].child.$refs.canvas.toDataURL();
        this.downloadBase64File(a, this.imageName);
      }
    },
  },
};
</script>

<style scoped></style>
