// The icons this site actually draws, as path data from @mdi/js.
//
// Vuetify's `mdi` icon set is the Material Design webfont: 300 KB of
// render-blocking CSS declaring all 7,462 icon classes, plus a 393 KB woff2,
// for the 72 icons below. plugins/vuetify-icons.js swaps it for an SVG set
// that reads this map, so `<v-icon>mdi-...</v-icon>` keeps working unchanged.
//
// Adding an icon to a template means adding it here. scripts/check-mdi-icons.js
// fails the build if the two drift apart.
import {
  mdiAccountClockOutline,
  mdiAccountMultipleOutline,
  mdiAlertCircleOutline,
  mdiArrowRight,
  mdiBookOpenPageVariantOutline,
  mdiBriefcaseOutline,
  mdiCalendarCheck,
  mdiCalendarRange,
  mdiCalendarStar,
  mdiCellphoneLock,
  mdiCertificateOutline,
  mdiChartBar,
  mdiChartBellCurveCumulative,
  mdiChartBox,
  mdiChartBoxOutline,
  mdiChartTimelineVariant,
  mdiChatProcessingOutline,
  mdiCheckCircleOutline,
  mdiCheckDecagram,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiClockCheckOutline,
  mdiClockFast,
  mdiClockTimeFourOutline,
  mdiClose,
  mdiCodeTags,
  mdiCog,
  mdiCounter,
  mdiEmoticonHappyOutline,
  mdiEmoticonOutline,
  mdiFile,
  mdiFileCertificateOutline,
  mdiFileDocumentOutline,
  mdiFileExport,
  mdiFileUploadOutline,
  mdiFormatLetterCase,
  mdiFormatLineSpacing,
  mdiFormatListNumbered,
  mdiFormatQuoteOpen,
  mdiGithub,
  mdiHeartOutline,
  mdiHomeHeart,
  mdiInformationOutline,
  mdiLightningBoltOutline,
  mdiLockOpenOutline,
  mdiMenu,
  mdiMessageTextOutline,
  mdiPartyPopper,
  mdiPassport,
  mdiPlayCircleOutline,
  mdiPlus,
  mdiReplyAllOutline,
  mdiRing,
  mdiScaleBalance,
  mdiShare,
  mdiShieldAlertOutline,
  mdiShieldCheckOutline,
  mdiShieldLockOutline,
  mdiSortClockAscendingOutline,
  mdiSpeedometer,
  mdiStarCircleOutline,
  mdiStarFourPointsOutline,
  mdiStarShootingOutline,
  mdiSwapHorizontal,
  mdiTextBoxSearchOutline,
  mdiTimerSand,
  mdiTimerSandComplete,
  mdiToolboxOutline,
  mdiTrayArrowDown,
  mdiWeatherNight,
  mdiWhiteBalanceSunny,
} from "@mdi/js";

export const mdiPaths = {
  "mdi-account-clock-outline": mdiAccountClockOutline,
  "mdi-account-multiple-outline": mdiAccountMultipleOutline,
  "mdi-alert-circle-outline": mdiAlertCircleOutline,
  "mdi-arrow-right": mdiArrowRight,
  "mdi-book-open-page-variant-outline": mdiBookOpenPageVariantOutline,
  "mdi-briefcase-outline": mdiBriefcaseOutline,
  "mdi-calendar-check": mdiCalendarCheck,
  "mdi-calendar-range": mdiCalendarRange,
  "mdi-calendar-star": mdiCalendarStar,
  "mdi-cellphone-lock": mdiCellphoneLock,
  "mdi-certificate-outline": mdiCertificateOutline,
  "mdi-chart-bar": mdiChartBar,
  "mdi-chart-bell-curve-cumulative": mdiChartBellCurveCumulative,
  "mdi-chart-box": mdiChartBox,
  "mdi-chart-box-outline": mdiChartBoxOutline,
  "mdi-chart-timeline-variant": mdiChartTimelineVariant,
  "mdi-chat-processing-outline": mdiChatProcessingOutline,
  "mdi-check-circle-outline": mdiCheckCircleOutline,
  "mdi-check-decagram": mdiCheckDecagram,
  "mdi-chevron-down": mdiChevronDown,
  "mdi-chevron-left": mdiChevronLeft,
  "mdi-chevron-right": mdiChevronRight,
  "mdi-clock-check-outline": mdiClockCheckOutline,
  "mdi-clock-fast": mdiClockFast,
  "mdi-clock-time-four-outline": mdiClockTimeFourOutline,
  "mdi-close": mdiClose,
  "mdi-code-tags": mdiCodeTags,
  "mdi-cog": mdiCog,
  "mdi-counter": mdiCounter,
  "mdi-emoticon-happy-outline": mdiEmoticonHappyOutline,
  "mdi-emoticon-outline": mdiEmoticonOutline,
  "mdi-file": mdiFile,
  "mdi-file-certificate-outline": mdiFileCertificateOutline,
  "mdi-file-document-outline": mdiFileDocumentOutline,
  "mdi-file-export": mdiFileExport,
  "mdi-file-upload-outline": mdiFileUploadOutline,
  "mdi-format-letter-case": mdiFormatLetterCase,
  "mdi-format-line-spacing": mdiFormatLineSpacing,
  "mdi-format-list-numbered": mdiFormatListNumbered,
  "mdi-format-quote-open": mdiFormatQuoteOpen,
  "mdi-github": mdiGithub,
  "mdi-heart-outline": mdiHeartOutline,
  "mdi-home-heart": mdiHomeHeart,
  "mdi-information-outline": mdiInformationOutline,
  "mdi-lightning-bolt-outline": mdiLightningBoltOutline,
  "mdi-lock-open-outline": mdiLockOpenOutline,
  "mdi-menu": mdiMenu,
  "mdi-message-text-outline": mdiMessageTextOutline,
  "mdi-party-popper": mdiPartyPopper,
  "mdi-passport": mdiPassport,
  "mdi-play-circle-outline": mdiPlayCircleOutline,
  "mdi-plus": mdiPlus,
  "mdi-reply-all-outline": mdiReplyAllOutline,
  "mdi-ring": mdiRing,
  "mdi-scale-balance": mdiScaleBalance,
  "mdi-share": mdiShare,
  "mdi-shield-alert-outline": mdiShieldAlertOutline,
  "mdi-shield-check-outline": mdiShieldCheckOutline,
  "mdi-shield-lock-outline": mdiShieldLockOutline,
  "mdi-sort-clock-ascending-outline": mdiSortClockAscendingOutline,
  "mdi-speedometer": mdiSpeedometer,
  "mdi-star-circle-outline": mdiStarCircleOutline,
  "mdi-star-four-points-outline": mdiStarFourPointsOutline,
  "mdi-star-shooting-outline": mdiStarShootingOutline,
  "mdi-swap-horizontal": mdiSwapHorizontal,
  "mdi-text-box-search-outline": mdiTextBoxSearchOutline,
  "mdi-timer-sand": mdiTimerSand,
  "mdi-timer-sand-complete": mdiTimerSandComplete,
  "mdi-toolbox-outline": mdiToolboxOutline,
  "mdi-tray-arrow-down": mdiTrayArrowDown,
  "mdi-weather-night": mdiWeatherNight,
  "mdi-white-balance-sunny": mdiWhiteBalanceSunny,
};
